// This file was generated by counterfeiter
package libfakes

import (
	"sync"

	"github.com/PredixDev/go-uaa-lib"
)

type FakeTokenClaimsFactoryInterface struct {
	NewStub        func(token string) (*lib.TokenClaims, error)
	newMutex       sync.RWMutex
	newArgsForCall []struct {
		token string
	}
	newReturns struct {
		result1 *lib.TokenClaims
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTokenClaimsFactoryInterface) New(token string) (*lib.TokenClaims, error) {
	fake.newMutex.Lock()
	fake.newArgsForCall = append(fake.newArgsForCall, struct {
		token string
	}{token})
	fake.recordInvocation("New", []interface{}{token})
	fake.newMutex.Unlock()
	if fake.NewStub != nil {
		return fake.NewStub(token)
	} else {
		return fake.newReturns.result1, fake.newReturns.result2
	}
}

func (fake *FakeTokenClaimsFactoryInterface) NewCallCount() int {
	fake.newMutex.RLock()
	defer fake.newMutex.RUnlock()
	return len(fake.newArgsForCall)
}

func (fake *FakeTokenClaimsFactoryInterface) NewArgsForCall(i int) string {
	fake.newMutex.RLock()
	defer fake.newMutex.RUnlock()
	return fake.newArgsForCall[i].token
}

func (fake *FakeTokenClaimsFactoryInterface) NewReturns(result1 *lib.TokenClaims, result2 error) {
	fake.NewStub = nil
	fake.newReturns = struct {
		result1 *lib.TokenClaims
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenClaimsFactoryInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.newMutex.RLock()
	defer fake.newMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeTokenClaimsFactoryInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ lib.TokenClaimsFactoryInterface = new(FakeTokenClaimsFactoryInterface)
