// This file was generated by counterfeiter
package libfakes

import (
	"sync"

	"github.com/PredixDev/go-uaa-lib"
)

type FakeInfoClientFactoryInterface struct {
	NewStub        func(url string, skipSslValidation bool, caCertFile string) lib.InfoClient
	newMutex       sync.RWMutex
	newArgsForCall []struct {
		url               string
		skipSslValidation bool
		caCertFile        string
	}
	newReturns struct {
		result1 lib.InfoClient
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeInfoClientFactoryInterface) New(url string, skipSslValidation bool, caCertFile string) lib.InfoClient {
	fake.newMutex.Lock()
	fake.newArgsForCall = append(fake.newArgsForCall, struct {
		url               string
		skipSslValidation bool
		caCertFile        string
	}{url, skipSslValidation, caCertFile})
	fake.recordInvocation("New", []interface{}{url, skipSslValidation, caCertFile})
	fake.newMutex.Unlock()
	if fake.NewStub != nil {
		return fake.NewStub(url, skipSslValidation, caCertFile)
	} else {
		return fake.newReturns.result1
	}
}

func (fake *FakeInfoClientFactoryInterface) NewCallCount() int {
	fake.newMutex.RLock()
	defer fake.newMutex.RUnlock()
	return len(fake.newArgsForCall)
}

func (fake *FakeInfoClientFactoryInterface) NewArgsForCall(i int) (string, bool, string) {
	fake.newMutex.RLock()
	defer fake.newMutex.RUnlock()
	return fake.newArgsForCall[i].url, fake.newArgsForCall[i].skipSslValidation, fake.newArgsForCall[i].caCertFile
}

func (fake *FakeInfoClientFactoryInterface) NewReturns(result1 lib.InfoClient) {
	fake.NewStub = nil
	fake.newReturns = struct {
		result1 lib.InfoClient
	}{result1}
}

func (fake *FakeInfoClientFactoryInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.newMutex.RLock()
	defer fake.newMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeInfoClientFactoryInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ lib.InfoClientFactoryInterface = new(FakeInfoClientFactoryInterface)
